// Package httpservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/flypay/go-kit/v4 version (devel) DO NOT EDIT.
package httpservice

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// User defines model for User.
type User struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

// UserAddJSONRequestBody defines body for UserAdd for application/json ContentType.
type UserAddJSONRequestBody = User
