openapi: 3.0.0
info:
  description: 'bootcamp-zoe-flower-slack-chatter'
  title: 'bootcamp-zoe-flower-slack-chatter'
  version: '0.0.1'
servers:
  - url: https://bootcamp-zoe-flower-slack-chatter.flyt-platform.com
    description: Production environment
  - url: https://bootcamp-zoe-flower-slack-chatter.flyt-staging.com
    description: Staging environment
  - url: https://bootcamp-zoe-flower-slack-chatter-{namespace}.flyt-dev.com
    description: Development environment
    variables:
      namespace:
        default: username
        description: The namespace of the development service, usually your username.

